[project]
name = "RAIRU"
version = "v0.1.1-alpha"
description = "Remote control"
authors = [
    { name="Tim Leung", email="timwork0314@gmail.com" }
]
dependencies = [
    "some_dependency>=1.0"
]

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.13,<4"]